# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=b'', max_length=120)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=20)),
                ('poted_steemit', models.BooleanField(default=False)),
                ('evaluado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
