# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Publicacion',
        ),
    ]
