# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180215_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
