# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20180215_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steemit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado_fecha', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=20)),
                ('votado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('publicado_fecha',),
            },
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='poted_steemit',
            new_name='curado',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='formateado',
            field=models.BooleanField(default=False),
        ),
    ]
