# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20180224_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='steemit',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
