# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_steemit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
