# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_publicacion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
