# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_publicacion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='categoria',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steemit',
            name='categoria',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
