# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-21 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20180421_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='steemit',
            name='votos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
