# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_steemit_votos'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrado_fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=180)),
                ('rol_redactor', models.CharField(max_length=180)),
                ('rol_curador', models.CharField(max_length=180)),
                ('reputacion', models.IntegerField()),
            ],
            options={
                'ordering': ('registrado_fecha',),
            },
        ),
    ]
