# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_comment', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=20)),
                ('parent_author', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('token', models.TextField()),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('image', models.TextField()),
                ('evaluated', models.BooleanField(default=False)),
                ('votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('permlink', models.TextField()),
                ('parent_permlink', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='Steemit',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('signup_date',)},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reputacion',
            new_name='down_votes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='registrado_fecha',
            new_name='signup_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol_curador',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol_redactor',
        ),
        migrations.AddField(
            model_name='user',
            name='presentation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
